---

- name: Install nfs kernel
  ansible.builtin.apt: 
    name: nfs-kernel-server
    state: latest
  become: "{{ become }}"

- name: Create Folder
  ansible.builtin.file:
    path: /mnt/network-file-system
    owner: root
    group: root
    mode: '0775'
    state: directory
  become: "{{ become }}"
  
- name: Add NFS export entry to /etc/exports
  ansible.builtin.shell: echo "/mnt/network-file-system *(rw,sync,no_subtree_check,no_root_squash)" | sudo tee -a /etc/exports
  become: "{{ become }}"
  notify: Restart nfs

  
    